### ISSUE TITLE
error compiling 

### ISSUE THREAD

**Issue by ghost** [kila58/qemu-patched#4]
hi, i have the following error codes when compiling, any suggestions on how to over come this?

FAILED: ui/dbus-display1.h ui/dbus-display1.c 
/usr/bin/gdbus-codegen ui/dbus-display1.xml --glib-min-required 2.64 --output-directory /home/user/qemu-patched/build/ui --interface-prefix org.qemu. --c-namespace QemuDBus --generate-c-code dbus-display1
Traceback (most recent call last):
  File "/usr/bin/gdbus-codegen", line 53, in <module>
    from codegen import codegen_main
  File "/usr/share/glib-2.0/codegen/codegen_main.py", line 30, in <module>
    from . import dbustypes
  File "/usr/share/glib-2.0/codegen/dbustypes.py", line 22, in <module>
    from . import utils
  File "/usr/share/glib-2.0/codegen/utils.py", line 22, in <module>
    import packaging.version
ModuleNotFoundError: No module named 'packaging'
ninja: build stopped: subcommand failed.
make: *** [Makefile:162: run-ninja] Error 1

**Comment by ghost** [comment]
i am on opensuse tumbleweed

**Comment by kila58** [comment]
Not too familiar with suse and it's python situation. Have you tried installing the package via pip? Is pip updated?

**Comment by ghost** [comment]
never mind issue resolved i reinstalled sphinx
